language: go

sudo: required
dist: trusty

go:
  - 1.5.3

env:
- GO15VENDOREXPERIMENT="1"

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

# skip godep restore
install:
  - true

notifications:
  slack: brief-team:ZTfvlvGvUloB7HIgyjVtZ4uO
